export enum ETokenType {
    EOF = 'EOF',
    NUMBER = 'NUMBER',
    PLUS = 'PLUS',
    MINUS = 'MINUS',
    MUL = 'MUL',
    DIV = 'DIV',
    LPAREN = 'LPAREN',
    RPAREN = 'RPAREN',
    RBRACKET = 'RBRACKET',
    LBRACKET = 'LBRACKET',
    ID = 'ID',
    ASSIGN = 'ASSIGN',
    SEMICOLON = 'SEMICOLON',
}
